helpwave/rest-api

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUST_TEMPLATE.md, .github/dependabot.yaml, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yaml, Dockerfile, README.md
This is @felbinger's PR (#4) but just his changes without any code from main. I did not want to mess with his branch hence this new PR.
Closes #4
=> Added Continuous Integration and CodeQL Analysis

.env.example, .gitignore, README.md, docker-compose.yaml, main.go, migrate.sh
Optimization of the documentation by updating the README.md, the environment variables and the process to set up a Postgres instance.
[The issue](https://github.com/helpwave/rest-api/issues/5)
Testing instructions:
1. Clone the project
2. Follow the instructions in the README.md until you start the rest-api
=> setup optimization

.github/CODEOWNERS
This will [auto-request code reviews from the team](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners) for new PRs
=> add backend team as CODEOWNER for repo

db/migrations/000001_init.down.sql, db/migrations/000001_init.up.sql, migrate.sh, models/department.go, models/emergency.go, models/point.go, models/room.go
Merge #15 first to avoid conflicts.
Closes #13
Questions related models and schemas should be done in a follow-up PR
=> Add models for ERs

docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, models/department.go, models/point.go, models/room.go, routes/pagination.go, routes/rooms.go, routes/util.go
=> ER stub endpoints

.github/workflows/ci.yaml, .gitignore
=> add swagger ci

.github/workflows/ci.yaml
=> chore(#34): fix swag ci

.editorconfig
=> feat(#39): add .editorconfig

docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, routes/auth.go, routes/rooms.go, routes/util.go
=> feat(#36): add auth middleware

docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, routes/rooms.go
=> feat(#20): add GetEmergencyRoomById

docs/docs.go, docs/swagger.json, docs/swagger.yaml, logging/gin.go, logging/gorm.go, logging/setup.go, models/emergency.go, models/setup.go, routes/auth.go, routes/healthz.go, routes/rooms.go, routes/util.go
=> feat(#44): fix formatting

Dockerfile, docker-compose.yml
=> Dockerization Refactoring

docs/docs.go, docs/swagger.json, docs/swagger.yaml, models/department.go, routes/rooms.go
=> Update Emergency Room Endpoint

.env.example, .github/workflows/ci.yaml, Dockerfile, README.md, docker-compose.prod.yml, docker-compose.yml, main.go
=> Fix Docker Issues

docker-compose.prod.yml, docker-compose.yml
The docker-compose file is invalid.
closes #63
=> fix: fix of wrong boolean type in docker-compose.yml #63

.github/workflows/ci.yaml
=> Fix deploy ci

routes/util.go
=> chore: remove dead code

docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, routes/departments.go, routes/pagination.go, routes/rooms.go, util/util.go
=> feat: add GET departments route

.github/workflows/ci.yaml
Closes #81
This time I actually tested it on a fork ^^
=> ci: fix broken swaggo ci yet again

docs/docs.go, docs/swagger.json, docs/swagger.yaml, models/department.go, models/point.go, models/questions.go, models/room.go, routes/departments.go, routes/util.go
=> docs: add examples to fields

main.go, models/department.go, models/emergency.go, models/organization.go, models/point.go, models/questions.go, models/room.go, models/user.go, routes/departments.go, routes/pagination.go, routes/rooms.go, routes/users.go, routes/util.go
=> feat: enforce camelCase in responses

.husky.yaml, Makefile, README.md
=> Lint git commit messages

auth/jwt.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml, main.go, routes/auth.go
Exchange the refresh-token for an access-token
Closes #97
=> feat: add refresh route
